Repository DEFRA/water-abstraction-service, pull requests merged in 2022-08, with the labels that each got.

#1749 Tidy up `package.json`
  package-lock.json
  package.json
Labels: housekeeping

#1754 Config 2nd instance to run background jobs
  config.js
  ecosystem.config.json
  index-background.js
  src/routes/background.js
  test/routes/background.test.js
Labels: enhancement

#1746 Hide `standard` linting commit
  .git-blame-ignore-revs
Labels: enhancement, housekeeping

#1757 Refactor CSV upload for performance
  src/modules/charge-versions-upload/lib/validator/index.js
Labels: housekeeping

#1758 Further CSV upload refactoring
  src/modules/charge-versions-upload/lib/validator/csvFields.js
  src/modules/charge-versions-upload/lib/validator/index.js
  src/modules/charge-versions-upload/lib/validator/tests.js
  test/modules/charge-versions-upload/lib/validator/validator.test.js
Labels: housekeeping

#1760 Refactor `update-charge-information-save` loop
  src/lib/services/charge-versions.js
  src/modules/charge-versions-upload/jobs/update-charge-information-save.js
Labels: housekeeping

#1762 Make charge version max upload consistent
  src/modules/charge-versions-upload/routes.js
Labels: housekeeping

#1764 Set log level using new env var
  .env.example
  config.js
Labels: housekeeping

#1772 Remove `config` folder
  package.json
  scripts/migrate-task-config/build-config-object.js
  scripts/migrate-task-config/hof-resume/config.json
  scripts/migrate-task-config/hof-resume/email.md
  scripts/migrate-task-config/hof-resume/letter.md
  scripts/migrate-task-config/hof-stop/config.json
  scripts/migrate-task-config/hof-stop/email.md
  scripts/migrate-task-config/hof-stop/letter.md
  scripts/migrate-task-config/hof-warning/config.json
  scripts/migrate-task-config/hof-warning/email.md
  scripts/migrate-task-config/hof-warning/letter.md
  scripts/migrate-task-config/migrate-task-config.js
  scripts/migrate-task-config/renewal/config.json
  scripts/migrate-task-config/renewal/email.md
  scripts/migrate-task-config/renewal/letter.md
Labels: housekeeping

#1771 Correctly set `NODE_ENV`
  .env.example
  config.js
  src/lib/connectors/crm/documents.js
  src/lib/connectors/crm/entities.js
  src/lib/connectors/notify.js
  src/lib/connectors/permit.js
  src/lib/connectors/returns.js
  src/lib/notify/index.js
  src/lib/slack.js
  src/modules/acceptance-tests/routes.js
  test/lib/connectors/notify.test.js
  test/lib/notify/index.test.js
Labels: housekeeping

#1776 Fix tests not using test redis DB
  config.js
Labels: bug

#1779 Minor housekeeping changes to root index files
  index-background.js
  index.js
  integration-tests/billing/services/scenarios.js
  test/controllers/notify.test.js
  test/controllers/sessions.test.js
  test/routes/water.test.js
Labels: housekeeping

#1781 Fix slow licence versions 4 charge workflow query
  src/lib/connectors/repos/queries/licence-versions.js
Labels: housekeeping

#1780 Remove node-cron for BullMQ jobs
  .env.example
  config.js
  src/modules/billing/jobs/check-for-updated-invoice-accounts.js
  src/modules/billing/register-subscribers.js
  src/modules/charge-versions/jobs/licence-not-in-charge-version-workflow.js
  src/modules/charge-versions/plugin.js
  test/modules/billing/jobs/check-for-updated-invoice-accounts.test.js
  test/modules/charge-versions/jobs/licence-not-in-charge-version-workflow.test.js
  test/modules/charge-versions/plugin.test.js
Labels: housekeeping

#1775 Refactor message-queue to centralise registration
  index.js
  src/lib/message-queue-v2/QueueManager.js
  src/lib/queue-manager/index.js
  src/lib/queue-manager/job-registration-service.js
  src/lib/queue-manager/queue-manager.js
  src/lib/queue-manager/start-up-jobs-service.js
  src/lib/services/invoice-account-addresses-service.js
  src/modules/acceptance-tests/lib/tear-down.js
  src/modules/batch-notifications/register-subscribers.js
  src/modules/billing/jobs/customer-file-refresh.js
  src/modules/billing/jobs/process-charge-version-year.js
  src/modules/billing/register-subscribers.js
  src/modules/billing/services/batch-service.js
  src/modules/billing/services/cm-refresh-service.js
  src/modules/billing/services/invoice-licences-service.js
  src/modules/charge-versions-upload/register-subscribers.js
  src/modules/charge-versions/jobs/licence-not-in-charge-version-workflow.js
  src/modules/charge-versions/plugin.js
  src/modules/gauging-stations/jobs/sync-gauging-stations.js
  src/modules/gauging-stations/jobs/sync-licence-gauging-stations-from-digitise.js
  src/modules/gauging-stations/jobs/sync-licence-version-purpose-conditions-from-digitise.js
  src/modules/gauging-stations/register-subscribers.js
  src/modules/returns/register-subscribers.js
  test/lib/queue-manager/index.test.js
  test/lib/queue-manager/job-registration-service.test.js
  test/lib/queue-manager/queue-manager.test.js
  test/lib/queue-manager/start-up-jobs-service.test.js
  test/lib/services/invoice-account-addresses-service.test.js
  test/modules/acceptance-tests/controller.test.js
  test/modules/billing/jobs/check-for-updated-invoice-accounts.test.js
  test/modules/billing/services/batch-service.test.js
  test/modules/billing/services/invoice-licences-service.test.js
  test/modules/charge-versions/plugin.test.js
Labels: housekeeping

#1784 Set up background tasks module
  ecosystem.config.json
  index-background.js
  index.js
  src/lib/queue-manager/queue-manager.js
  src/modules/billing/jobs/process-charge-version-year.js
  src/modules/billing/jobs/update-invoices.js
  test/lib/queue-manager/queue-manager.test.js
Labels: enhancement

#1786 Replace supported source sync with migration
  config.js
  migrations/20220823105615-upsert-billing-supported-sources.js
  migrations/sqls/20220823105615-upsert-billing-supported-sources-down.sql
  migrations/sqls/20220823105615-upsert-billing-supported-sources-up.sql
  src/lib/queue-manager/job-registration-service.js
  src/lib/queue-manager/start-up-jobs-service.js
  src/modules/billing/jobs/sync-supported-sources.js
  test/modules/billing/jobs/sync-supported-sources.test.js
Labels: housekeeping

#1708 Remove unneeded dependencies
  package-lock.json
  package.json
  src/lib/connectors/external-http.js
  src/modules/billing/routes/invoice-licences.js
Labels: housekeeping

#1787 Add `isBackground` flag to `config.js`
  config.js
  src/lib/queue-manager/queue-manager.js
  src/modules/billing/jobs/process-charge-version-year.js
  src/modules/billing/jobs/update-invoices.js
  test/lib/queue-manager/queue-manager.test.js
Labels: housekeeping

#1794 Remove catbox-redis from service
  index.js
  package-lock.json
  package.json
  src/modules/address-search/controller.js
  src/modules/address-search/plugin.js
  test/modules/address-search/controller.test.js
  test/modules/address-search/plugin.test.js
Labels: housekeeping

#1796 Fix port conflict with test
  test/routes/background.test.js
  test/routes/water.test.js
Labels: bug

#1736 Fix failing Dependabot tests
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/modules/notify/controller.js
  test/controllers/notify.test.js
  test/modules/notify/controller.test.js
  test/modules/notify/index.test.js
Labels: housekeeping
