Repository DEFRA/water-abstraction-service, pull requests merged in 2022-09, with the labels that each got.

#1793 Amend purpose use validation from charge upload
  migrations/20220831134406-remove-purposes-null-constraint.js
  migrations/sqls/20220831134406-remove-purposes-null-constraint-down.sql
  migrations/sqls/20220831134406-remove-purposes-null-constraint-up.sql
  src/modules/charge-versions-upload/lib/helpers.js
  src/modules/charge-versions-upload/lib/mapper/chargePurposesMapper.js
  src/modules/charge-versions-upload/lib/mapper/chargeVersionMapper.js
  src/modules/charge-versions-upload/lib/validator/tests.js
  test/modules/charge-versions-upload/lib/mapper/chargePurposesMapper.test.js
  test/modules/charge-versions-upload/lib/mapper/chargeVersionMapper.test.js
  test/modules/charge-versions-upload/lib/validator/validator.test.js
Labels: enhancement

#1806 SRoC annual billing - pro rata calculations not calculating as expected
  src/modules/billing/mappers/transaction.js
  test/modules/billing/mappers/transaction.test.js
Labels: bug

#1811 Fix `libxmljs` unit tests
  test/modules/returns/lib/xml-adapter/mapper.test.js
  test/modules/returns/lib/xml-adapter/validator.test.js
  test/modules/returns/lib/xml-to-json-integration.test.js
Labels: housekeeping

#1812 Fix libxmljs update issue
  package.json
  scripts/fix-libxmljs-location.sh
Labels: bug

#1817 Remove unused getFinancialYears function
  src/lib/models/financial-year.js
  test/lib/models/financial-year.test.js
Labels: housekeeping

#1814 Remove `src/lib/response.js`
  src/lib/response.js
  src/modules/billing/controllers/batches.js
  src/modules/billing/controllers/two-part-tariff-review.js
  src/modules/companies/controller.js
  test/lib/response.test.js
Labels: housekeeping

#1831 Remove docker files from repos
  .dockerignore
  Dockerfile
Labels: housekeeping

#1832 Fix pm2 logs for service-background not combining
  ecosystem.config.json
Labels: bug
