Repository DEFRA/water-abstraction-service, pull requests merged in 2022-10, with the labels that each got.

#1853 Fix problem licence data
  migrations/20221017134036-remove-problem-licences.js
  migrations/sqls/20221017134036-remove-problem-licences-down.sql
  migrations/sqls/20221017134036-remove-problem-licences-up.sql
Labels: bug

#1857 Make `auto-changelog` external
  package-lock.json
  package.json
Labels: housekeeping

#1858 Revert changelog script change with improvements
  package.json
Labels: housekeeping

#1862 Create health status endpoint
  src/modules/health/controller.js
  src/modules/health/routes.js
  src/modules/routes.js
  test/modules/health/controller.test.js
Labels: enhancement

#1864 Rename health status endpoint
  src/modules/health/controller.js
  src/modules/health/routes.js
  test/modules/health/controller.test.js
Labels: housekeeping

#1865 Add health route to background service
  src/routes/background.js
Labels: enhancement

#1868 Add new SROC supplementary billing test data
  integration-tests/billing/fixtures/sets.json
  integration-tests/billing/fixtures/sroc-charge-info.yaml
  integration-tests/billing/fixtures/sroc-crm-v1.yaml
  integration-tests/billing/fixtures/sroc-crm-v2.yaml
  integration-tests/billing/fixtures/sroc-licences.yaml
  integration-tests/billing/fixtures/sroc-permits.yaml
  integration-tests/billing/fixtures/sroc-users.yaml
  integration-tests/billing/services/bookshelf-loader.js
Labels: enhancement

#1870 Add new presroc billing acc. change to fixture
  integration-tests/billing/fixtures/sets.json
  integration-tests/billing/fixtures/sroc-charge-info.yaml
  integration-tests/billing/fixtures/sroc-crm-v1.yaml
  integration-tests/billing/fixtures/sroc-crm-v2.yaml
  integration-tests/billing/fixtures/sroc-licences.yaml
  integration-tests/billing/fixtures/sroc-permits.yaml
  integration-tests/billing/fixtures/sroc-purposes.yaml
Labels: enhancement

#1871 Add SROC sup. billing scenario 3 fixture data
  integration-tests/billing/fixtures/sroc-charge-info.yaml
  integration-tests/billing/fixtures/sroc-crm-v1.yaml
  integration-tests/billing/fixtures/sroc-crm-v2.yaml
  integration-tests/billing/fixtures/sroc-licences.yaml
  integration-tests/billing/fixtures/sroc-permits.yaml
Labels: testing
