Repository DEFRA/water-abstraction-service, pull requests merged in 2022-07, with the labels that each got.

#1709 Fix non-prod delete all bill runs function
  src/modules/billing/routes/batches.js
Labels: bug

#1710 Apply consistent CI workflow
  .github/workflows/ci.yml
  .labrc.js
  README.MD
  package.json
  sonar-project.properties
Labels: housekeeping

#1713 Add dependabot.yml config file
  .github/dependabot.yml
Labels: housekeeping

#1715 Make gitignore consistent with other projects
  .gitignore
Labels: housekeeping

#1719 Remove snyk exception config
  .snyk
Labels: housekeeping

#1712 Move db-migrate packages
  package-lock.json
  package.json
Labels: housekeeping

#1722 Persist data for sroc bill run CSV export
  src/modules/billing/mappers/transaction.js
Labels: bug, enhancement

#1728 Add Delete All Billing Data environment variable
  .env.example
  config.js
Labels: enhancement

#1737 Addition of mBOD as a unit type in the tagging flow
  src/modules/gauging-stations/routes/index.js
  test/modules/gauging-stations/routes.test.js
Labels: enhancement

#1738 SRoC charge creation - additional characters required in charge reference description
  src/modules/charge-versions-upload/lib/validator/tests.js
  test/modules/charge-versions-upload/lib/validator/validator.test.js
Labels: enhancement

#1739 Handle 0 Volumes
  src/modules/charge-categories/routes.js
  src/modules/charge-versions-upload/lib/validator/csvFields.js
  src/modules/charge-versions-upload/lib/validator/tests.js
  test/modules/charge-categories/routes.test.js
  test/modules/charge-versions-upload/lib/validator/validator.test.js
Labels: enhancement

#1744 Sroc upload -- allow public water only for water undertakers
  src/modules/charge-versions-upload/lib/helpers.js
  src/modules/charge-versions-upload/lib/validator/csvFields.js
  src/modules/charge-versions-upload/lib/validator/tests.js
  test/modules/charge-versions-upload/lib/validator/validator.test.js
Labels: enhancement
