Repository DEFRA/water-abstraction-service, pull requests merged in 2022-11, with the labels that each got.

#1883 Remove swagger dependency
  .labrc.js
  config.js
  index.js
  package-lock.json
  package.json
Labels: housekeeping

#1888 Replace deprecated set-output cmd in GitHub CI
  .github/workflows/ci.yml
Labels: housekeeping

#1889 Remove pm2 watch config from ecosystem file
  ecosystem.config.json
Labels: housekeeping

#1894 Data migration fix for leap year charge purposes
  migrations/20221122000155-fix-leap-year-charge-purposes.js
  migrations/sqls/20221122000155-fix-leap-year-charge-purposes-down.sql
  migrations/sqls/20221122000155-fix-leap-year-charge-purposes-up.sql
Labels: bug

#1900 Fix cancelling billing batch error
  src/modules/billing/services/batch-service.js
  test/modules/billing/services/batch-service.test.js
Labels: bug

#1902 Update water-abstraction-helpers to latest version
  package-lock.json
  package.json
Labels: dependencies
