Repository DEFRA/water-abstraction-service, pull requests merged in 2022-12, with the labels that each got.

#1905 Move test database URL to environment variable
  .env.example
  .github/workflows/ci.yml
  config.js
  package.json
  scripts/migrate.js
Labels: enhancement

#1908 Bill numbers not showing on Bills Screen
  migrations/20221201120136-fix-missing-numbers.js
  migrations/sqls/20221201120136-fix-missing-numbers-down.sql
  migrations/sqls/20221201120136-fix-missing-numbers-up.sql
  scripts/migrate.js
Labels: bug

#1920 Remove hapi good - add hapi-pino
  config.js
  index-background.js
  index.js
  package-lock.json
  package.json
  src/lib/services/hapi-pino-ignore-request.service.js
  src/plugins/hapi-pino.plugin.js
  test/lib/services/hapi-pino-ignore-request.service.test.js
Labels: housekeeping

#1924 Add new SROC test fixture
  integration-tests/billing/fixtures/sroc-charge-info.yaml
  integration-tests/billing/fixtures/sroc-crm-v1.yaml
  integration-tests/billing/fixtures/sroc-crm-v2.yaml
  integration-tests/billing/fixtures/sroc-licences.yaml
  integration-tests/billing/fixtures/sroc-permits.yaml
Labels: enhancement
