Repository DEFRA/water-abstraction-service, pull requests merged in 2023-07, with the labels that each got.

#2203 Use the correct values from CM to populate DB
  src/modules/billing/jobs/lib/update-invoices-worker.js
Labels: bug

#2204 Tell Got to retry PATCH requests
  src/lib/connectors/charge-module/lib/got-with-proxy.js
Labels: housekeeping

#2205 Add remove job method to QueueManager
  src/lib/queue-manager/queue-manager.js
  src/modules/billing/controllers/batches.js
  test/lib/queue-manager/queue-manager.test.js
  test/modules/billing/controllers/batches.test.js
Labels: enhancement

#2207 Fix stuck Midlands sending bill run
  migrations/20230710065510-fix-stuck-sending-bill-run.js
  migrations/sqls/20230710065510-fix-stuck-sending-bill-run-down.sql
  migrations/sqls/20230710065510-fix-stuck-sending-bill-run-up.sql
Labels: bug

#2213 Fix `update-invoices-worker` for sroc reissuing
  src/modules/billing/jobs/lib/update-invoices-worker.js
Labels: enhancement
