Repository DEFRA/water-abstraction-service, pull requests merged in 2023-04, with the labels that each got.

#2083 Remove 'truncate', 'max' and 'maxBy' Lodash function
  src/lib/mappers/charge-category.js
  src/lib/mappers/charge-module.js
  src/lib/mappers/supported-source.js
  src/lib/models/charge-element.js
  src/lib/models/charge-purpose.js
  src/lib/object-helpers.js
  src/modules/returns/lib/nald-returns-mapper.js
Labels: enhancement

#2094 Revert Puppeteer to 19.8.0
  package-lock.json
  package.json
Labels: bug

#2093 Remove 'groupBy' and 'mapValues' Lodash function
  integration-tests/billing/services/fixture-loader/FixtureLoader.js
  src/lib/object-helpers.js
  src/lib/stringify-values.js
  src/modules/batch-notifications/config/returns/lib/return-notification-contacts.js
  src/modules/batch-notifications/config/returns/lib/return-notification-recipients.js
  src/modules/billing/services/charge-processor-service/lib/agreements.js
  src/modules/billing/services/supplementary-billing-service/data-service.js
  src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
  src/modules/billing/services/volume-matching-service/models/charge-element-group.js
  src/modules/billing/services/volume-matching-service/return-group-service.js
  src/modules/internal-search/lib/search-returns.js
  src/modules/notify/connectors/scheduled-notification.js
  test/lib/models/contact.test.js
Labels: housekeeping

#2086 Remove 'startCase' and 'isEqual' lodash function
  src/modules/billing/services/batch-service.js
  src/modules/charge-versions-upload/lib/mapper/adjustmentsMapper.js
  src/modules/charge-versions-upload/lib/validator/index.js
  src/modules/gauging-stations/helpers.js
  src/modules/returns/lib/returns-upload-validator.js
Labels: housekeeping

#2089 Remove 'reverse', 'compact', 'isFinite', 'pickBy' and 'orderBy' Lodash function
  src/lib/models/licence.js
  src/lib/models/return-version.js
  src/lib/services/crm-service.js
  src/lib/services/invoice-service.js
  src/modules/batch-notifications/lib/notify-helpers.js
  src/modules/billing/services/charge-processor-service/lib/agreements.js
  src/modules/returns/lib/csv-adapter/date-parser.js
  src/modules/returns/lib/csv-adapter/validator.js
Labels: housekeeping

#2096 Refactor Lodash Code Changes
  src/lib/stringify-values.js
  src/modules/batch-notifications/config/returns/lib/get-recipients.js
  src/modules/notify/connectors/scheduled-notification.js
  test/lib/stringify-values.test.js
Labels: housekeeping

#2116 Supplementary Billing - Too many previous years
  src/modules/billing/services/batch-service.js
Labels: bug

#2118 Supplementary Billing - Too many previous years
  src/modules/billing/services/batch-service.js
Labels: bug

#2122 Fix error in Batch Notifications Refresh event job
  src/modules/batch-notifications/lib/event-helpers.js
  test/modules/batch-notifications/lib/event-helpers.test.js
Labels: bug
