Repository DEFRA/water-abstraction-service, pull requests merged in 2023-03, with the labels that each got.

#2039 Fix missing adjustments in SROC test fixture data
  integration-tests/billing/fixtures/sroc-charge-info.yaml
Labels: bug

#2036 Add new batch refresh totals endpoint
  src/modules/billing/controllers/batches.js
  src/modules/billing/routes/batches.js
  test/modules/billing/controllers/batches.test.js
  test/modules/billing/routes/batches.test.js
Labels: enhancement

#2017 Remove 'set' lodash function
  src/lib/connectors/ea-address-facade.js
  src/lib/validate.js
  src/modules/batch-notifications/lib/event-helpers.js
  src/modules/charge-versions-upload/jobs/update-charge-information-save.js
  src/modules/charge-versions-upload/lib/error-event.js
  src/modules/charge-versions-upload/lib/helpers.js
  src/modules/charge-versions-upload/lib/mapper/index.js
  src/modules/internal-search/lib/build-response.js
  src/modules/returns/controllers/csv-upload.js
  src/modules/returns/lib/jobs/error-event.js
  src/modules/returns/lib/jobs/persist-returns.js
  src/modules/returns/lib/jobs/validate-returns.js
  test/lib/mappers/charge-module.test.js
  test/modules/billing/services/invoice-licences-service.test.js
  test/modules/companies/lib/returns.test.js
  test/modules/gauging-stations/jobs/sync-gauging-stations.test.js
  test/modules/internal-search/lib/search-users.test.js
  test/modules/returns/lib/returns-upload-validator.test.js
Labels: housekeeping

#2052 Make request logging configurable & change default
  config.js
  src/plugins/hapi-pino.plugin.js
Labels: housekeeping

#2056 Remove constraint from `billing_transactions` table
  migrations/20230315122011-remove-constraint-from-billing-transactions.js
  migrations/sqls/20230315122011-remove-constraint-from-billing-transactions-down.sql
  migrations/sqls/20230315122011-remove-constraint-from-billing-transactions-up.sql
Labels: bug

#2057 Fix SROC invoices flagged for re-issue
  src/lib/connectors/repos/queries/billing-invoices.js
Labels: bug

#2050 Remove lodash code
  src/lib/camel-case-keys.js
  src/lib/services/to-camel-case.js
  src/modules/charge-versions-upload/lib/mapper/index.js
  src/modules/communications/controller.js
  src/modules/service-status/controller.js
Labels: housekeeping

#2061 Remove 'uniq' lodash function
  src/lib/models/invoice.js
  src/lib/services/returns/returns-mapping-service.js
  src/modules/batch-notifications/config/returns/lib/get-recipients.js
  src/modules/batch-notifications/config/returns/lib/return-notification-recipients.js
  src/modules/batch-notifications/lib/event-helpers.js
  src/modules/billing/controllers/batches.js
  src/modules/billing/services/charge-version-service/two-part-tariff-seasons.js
  src/modules/billing/services/licences-service.js
  src/modules/internal-search/lib/search-documents.js
  src/modules/notifications/lib/event-factory.js
  src/modules/returns-notifications/controller.js
  src/modules/returns-notifications/lib/event-factory.js
  src/modules/returns/controllers/controller.js
  src/modules/returns/lib/returns-upload-validator.js
  src/modules/returns/lib/xml-adapter/mapper.js
Labels: housekeeping

#2065 Remove 'chunk' lodash function
  src/lib/chunk.js
  src/lib/connectors/crm-v2/invoice-accounts.js
  src/lib/connectors/crm/documents.js
  src/lib/connectors/idm.js
  src/lib/connectors/returns.js
  src/lib/mappers/lib/helpers.js
  src/lib/services/pdf-generation/view-helpers.js
  src/modules/batch-notifications/config/returns/lib/return-notification-contacts.js
  src/modules/returns/lib/returns-upload-validator.js
Labels: housekeeping

#2059 Remove 'isFunction' and 'identity' lodash functions
  src/lib/mappers/charge-module.js
  src/lib/mappers/contact.js
  src/lib/models/address.js
  src/lib/models/transaction.js
  src/lib/object-mapper.js
  src/lib/services/returns/index.js
  src/modules/batch-notifications/config/returns/lib/return-notification-recipients.js
  src/modules/billing/lib/charge-period.js
  src/modules/billing/mappers/transaction.js
  src/modules/billing/services/volume-matching-service/models/return-group.js
  src/modules/gauging-stations/helpers.js
  src/modules/notifications/lib/notification-factory.js
  test/modules/gauging-stations/jobs/sync-gauging-stations.test.js
Labels: housekeeping

#2071 Remove constraint from `billing_invoice_licences` table
  migrations/20230322114830-remove-constraint-from-billing-invoice-licences.js
  migrations/sqls/20230322114830-remove-constraint-from-billing-invoice-licences-down.sql
  migrations/sqls/20230322114830-remove-constraint-from-billing-invoice-licences-up.sql
Labels: bug

#2068 Refactor removal of lodash code
  src/lib/camel-case-keys.js
  src/lib/chunk.js
  src/lib/connectors/crm-v2/invoice-accounts.js
  src/lib/connectors/crm/documents.js
  src/lib/connectors/crm/entities.js
  src/lib/connectors/idm.js
  src/lib/connectors/returns.js
  src/lib/mappers/lib/helpers.js
  src/lib/object-helpers.js
  src/lib/partial-right.js
  src/lib/services/invoice-service.js
  src/lib/services/pdf-generation/view-helpers.js
  src/lib/services/to-camel-case.js
  src/modules/batch-notifications/config/returns/lib/return-notification-contacts.js
  src/modules/billing/jobs/lib/batch-status.js
  src/modules/billing/services/batch-service.js
  src/modules/charge-versions-upload/lib/mapper/index.js
  src/modules/communications/controller.js
  src/modules/returns/lib/returns-upload-validator.js
  src/modules/service-status/controller.js
Labels: housekeeping

#2077 Add SROC include in supplementary billing flag
  migrations/20230327150452-add-include-in-sroc-supplementary-billing-flag.js
  migrations/sqls/20230327150452-add-include-in-sroc-supplementary-billing-flag-down.sql
  migrations/sqls/20230327150452-add-include-in-sroc-supplementary-billing-flag-up.sql
  src/lib/mappers/licence.js
  src/lib/services/licences.js
  src/modules/charge-versions/services/charge-version-workflows.js
  test/lib/mappers/licence.test.js
  test/lib/services/licences.test.js
  test/modules/charge-versions/services/charge-version-workflows.test.js
Labels: enhancement

#2073 Remove 'reduce' and 'sortBy' lodash function
  src/lib/camel-case-keys.js
  src/lib/models/invoice-account.js
  src/lib/services/charge-versions.js
  src/modules/address-search/services/address-service.js
  src/modules/billing/lib/charge-period.js
  src/modules/billing/services/charge-processor-service/lib/agreements.js
  src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
  src/modules/billing/services/volume-matching-service/models/charge-element-group.js
  src/modules/charge-versions-upload/lib/mapper/index.js
  src/modules/charge-versions-upload/lib/validator/index.js
  test/modules/address-search/services/address-service.test.js
Labels: housekeeping

#2082 Remove 'flatMap' Lodash function
  src/lib/connectors/crm-v2/invoice-accounts.js
  src/lib/connectors/crm/documents.js
  src/lib/connectors/returns.js
  src/lib/models/invoice.js
  src/lib/services/returns/index.js
  src/modules/batch-notifications/config/returns/lib/return-notification-recipients.js
  src/modules/billing/controllers/batches.js
  src/modules/billing/services/charge-processor-service/lib/agreements.js
  src/modules/billing/services/charge-processor-service/transactions-processor.js
  src/modules/billing/services/charge-version-service/index.js
  src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
  src/modules/billing/services/transactions-service.js
  src/modules/billing/services/volume-matching-service/models/charge-element-group.js
  src/modules/returns/lib/csv-adapter/date-parser.js
  src/modules/returns/lib/returns-upload-validator.js
  src/modules/returns/lib/xml-adapter/mapper.js
  test/modules/billing/services/volume-matching-service/models/charge-element-group.test.js
Labels: housekeeping

#2080 Clear Include In SROC supp. billing flag on send
  src/lib/connectors/repos/licences.js
  src/lib/connectors/repos/queries/licences.js
  src/lib/services/licences.js
  src/modules/billing/services/batch-service.js
  test/lib/connectors/repos/licences.test.js
  test/modules/billing/services/batch-service.test.js
Labels: enhancement

#2088 Migration to flag sroc supp. billing invoices
  migrations/20230331071630-flag-include-sroc-supplementary.js
  migrations/sqls/20230331071630-flag-include-sroc-supplementary-down.sql
  migrations/sqls/20230331071630-flag-include-sroc-supplementary-up.sql
Labels: housekeeping
