Repository DEFRA/water-abstraction-service, pull requests merged in 2023-10, with the labels that each got.

#2293 Improve Bill Run Queue Handling to Prevent Duplicate Jobs
  src/modules/billing/jobs/approve-batch.js
  test/modules/billing/jobs/approve-batch.test.js
Labels: bug

#2300 Remove presroc supp. billing flag migration
  migrations/20231006152321-unflag-presroc-flag-selected-licences.js
  migrations/sqls/20231006152321-unflag-presroc-flag-selected-licences-down.sql
  migrations/sqls/20231006152321-unflag-presroc-flag-selected-licences-up.sql
Labels: housekeeping

#2305 Prevent error page showing for multiple return invitation requests
  src/modules/batch-notifications/lib/send-batch.js
  test/modules/batch-notifications/lib/send-batch.test.js
Labels: enhancement

#2295 Improve Hand-Off Flow Notification Handling
  migrations/20231002164902-add-notification-types-and-job-id.js
  migrations/sqls/20231002164902-add-notification-types-and-job-id-down.sql
  migrations/sqls/20231002164902-add-notification-types-and-job-id-up.sql
  src/modules/notifications/controller.js
  src/modules/notifications/lib/index.js
  src/modules/notify/index.js
  src/modules/notify/lib/helpers.js
Labels: enhancement

#2312 Stop duplicate paper forms
  src/modules/batch-notifications/config/paper-returns/index.js
  src/modules/batch-notifications/controller.js
Labels: enhancement
