Repository DEFRA/water-abstraction-service, pull requests merged in 2024-04, with the labels that each got.

#2484 Update SROC test data to always include annual
  integration-tests/billing/fixtures/sets.json
  integration-tests/billing/fixtures/sroc-annual-bill-run.yaml
  integration-tests/billing/services/fixture-loader/FixtureLoader.js
Labels: testing

#2494 Remove billing.find-update-invoice-accounts job
  config.js
  src/lib/connectors/crm-v2/invoice-accounts.js
  src/lib/queue-manager/job-registration-service.js
  src/lib/queue-manager/start-up-jobs-service.js
  src/modules/billing/jobs/check-for-updated-invoice-accounts.js
  test/lib/connectors/crm-v2/invoice-accounts.test.js
  test/lib/queue-manager/start-up-jobs-service.test.js
  test/modules/billing/jobs/check-for-updated-invoice-accounts.test.js
Labels: housekeeping

#2497 Identify workflow setup records with chg versions
  migrations/20240415100933-tag-updated-to-setup-workflows.js
  migrations/sqls/20240415100933-tag-updated-to-setup-workflows-down.sql
  migrations/sqls/20240415100933-tag-updated-to-setup-workflows-up.sql
Labels: housekeeping

#2511 Add column to `licences` table to flag for 2PT supplementary billing
  migrations/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag.js
  migrations/sqls/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag-down.sql
  migrations/sqls/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag-up.sql
Labels: enhancement
