Repository DEFRA/water-abstraction-service, pull requests merged in 2024-08, with the labels that each got.

#2598 Add mod_log fields 2 return, licence & charge ver.
  migrations/20240809155344-water-versions-add-mod-log-column.js
  migrations/sqls/20240809155344-water-versions-add-mod-log-column-down.sql
  migrations/sqls/20240809155344-water-versions-add-mod-log-column-up.sql
Labels: enhancement

#2601 Fix type defaults on the water notes table
  migrations/20240812135353-alter-water-notes.js
  migrations/sqls/20240812135353-alter-water-notes-down.sql
  migrations/sqls/20240812135353-alter-water-notes-up.sql
Labels: housekeeping

#2600 Add System config for Supplementary billing flags
  .env.example
  config.js
  src/lib/connectors/system/supplementary-billing.js
  src/lib/services/charge-versions.js
  test/lib/services/charge-versions.test.js
Labels: enhancement

#2605 Add migration for licence versions and licence versions purposes
  migrations/20240814102304-alter-licence-version-created-and-updated-at.js
  migrations/20240814103242-alter-licence-version-purposes-created-and-updated-at.js
  migrations/sqls/20240814102304-alter-licence-version-created-and-updated-at-down.sql
  migrations/sqls/20240814102304-alter-licence-version-created-and-updated-at-up.sql
  migrations/sqls/20240814103242-alter-licence-version-purposes-created-and-updated-at-down.sql
  migrations/sqls/20240814103242-alter-licence-version-purposes-created-and-updated-at-up.sql
Labels: enhancement

#2606 Add new `batch_type` for TPT supplementary to DB
  migrations/20240814134405-alter-water-charge-batch-type.js
  migrations/sqls/20240814134405-alter-water-charge-batch-type-down.sql
  migrations/sqls/20240814134405-alter-water-charge-batch-type-up.sql
Labels: enhancement

#2609 Fix external change user email journey
  src/modules/change-email/controller.js
  src/modules/change-email/lib/helpers.js
  test/modules/change-email/controller.test.js
  test/modules/change-email/lib/helpers.test.js
Labels: bug

#2611 Handle failed request to system supplementary
  src/lib/services/charge-versions.js
Labels: housekeeping

#2608 Update Supplementary Billing flag route
  src/lib/connectors/system/supplementary-billing.js
Labels: housekeeping

#2612 Alter name & default for versions `mod_log` field
  migrations/20240816144249-alter-versions-mod-log-column.js
  migrations/sqls/20240816144249-alter-versions-mod-log-column-down.sql
  migrations/sqls/20240816144249-alter-versions-mod-log-column-up.sql
Labels: housekeeping

#2615 Replace mod_logs columns with a table - for real!
  migrations/20240816144249-alter-versions-mod-log-column.js
  migrations/20240819083436-water-add-mod-logs.js
  migrations/sqls/20240809155344-water-versions-add-mod-log-column-down.sql
  migrations/sqls/20240809155344-water-versions-add-mod-log-column-up.sql
  migrations/sqls/20240816144249-alter-versions-mod-log-column-down.sql
  migrations/sqls/20240816144249-alter-versions-mod-log-column-up.sql
  migrations/sqls/20240819083436-water-add-mod-logs-down.sql
  migrations/sqls/20240819083436-water-add-mod-logs-up.sql
Labels: enhancement

#2616 Delete errant licence version
  migrations/20240819214901-fix-errant-licence-version.js
  migrations/sqls/20240819214901-fix-errant-licence-version-down.sql
  migrations/sqls/20240819214901-fix-errant-licence-version-up.sql
Labels: bug

#2623 Remove presroc supp. billing flag migration
  migrations/20240823131709-unflag-presroc-flag-selected-licences.js
  migrations/sqls/20240823131709-unflag-presroc-flag-selected-licences-down.sql
  migrations/sqls/20240823131709-unflag-presroc-flag-selected-licences-up.sql
Labels: housekeeping

#2626 Add a new licence version purpose points table
  migrations/20240827145508-water-add-licence-version-purpose-points-table.js
  migrations/sqls/20240827145508-water-add-licence-version-purpose-points-table-down.sql
  migrations/sqls/20240827145508-water-add-licence-version-purpose-points-table-up.sql
Labels: enhancement
