Repository DEFRA/water-abstraction-service, pull requests merged in 2024-11, with the labels that each got.

#2654 Move 2PT review result tables into 'water' schema
  migrations/20241110124720-create-licence-supplementary-years-table.js
  migrations/20241110130306-create-review-charge-elements-table.js
  migrations/20241110131320-create-review-charge-element-returns-table.js
  migrations/20241110140334-create-review-charge-references-table.js
  migrations/20241110141632-create-review-charge-versions-table.js
  migrations/20241110142207-create-review-licences-table.js
  migrations/20241110142817-create-review-returns-table.js
  migrations/sqls/20241110124720-create-licence-supplementary-years-table-down.sql
  migrations/sqls/20241110124720-create-licence-supplementary-years-table-up.sql
  migrations/sqls/20241110130306-create-review-charge-elements-table-down.sql
  migrations/sqls/20241110130306-create-review-charge-elements-table-up.sql
  migrations/sqls/20241110131320-create-review-charge-element-returns-table-down.sql
  migrations/sqls/20241110131320-create-review-charge-element-returns-table-up.sql
  migrations/sqls/20241110140334-create-review-charge-references-table-down.sql
  migrations/sqls/20241110140334-create-review-charge-references-table-up.sql
  migrations/sqls/20241110141632-create-review-charge-versions-table-down.sql
  migrations/sqls/20241110141632-create-review-charge-versions-table-up.sql
  migrations/sqls/20241110142207-create-review-licences-table-down.sql
  migrations/sqls/20241110142207-create-review-licences-table-up.sql
  migrations/sqls/20241110142817-create-review-returns-table-down.sql
  migrations/sqls/20241110142817-create-review-returns-table-up.sql
Labels: housekeeping

#2653 Add quarterly returns to return versions table
  migrations/20241107093135-add-quarterly-returns-to-return-versions.js
  migrations/sqls/20241107093135-add-quarterly-returns-to-return-versions-down.sql
  migrations/sqls/20241107093135-add-quarterly-returns-to-return-versions-up.sql
Labels: enhancement

#2660 Move return versions to correct licence
  migrations/20241126154953-fix-miss-linked-return-versions.js
  migrations/sqls/20241126154953-fix-miss-linked-return-versions-down.sql
  migrations/sqls/20241126154953-fix-miss-linked-return-versions-up.sql
Labels: bug
