Repository DEFRA/water-abstraction-service, pull requests merged in 2025-05, with the labels that each got.

#2687 Remove charge categories sync job
  src/lib/queue-manager/start-up-jobs-service.js
Labels: housekeeping

#2688 Actually stop charge categories sync job!
  src/lib/queue-manager/job-registration-service.js
  src/modules/billing/jobs/sync-charge-categories.js
  test/modules/billing/jobs/sync-charge-categories.test.js
Labels: housekeeping

#2689 Fix "Build Status" badge
  README.MD
Labels: documentation

#2690 Migration - Add `created_by` to `licence_gauging_stations`
  migrations/20250512143930-alter-licence-gauging-stations.js
  migrations/sqls/20250512143930-alter-licence-gauging-stations-down.sql
  migrations/sqls/20250512143930-alter-licence-gauging-stations-up.sql
Labels: enhancement

#2692 Update returns for company endpoint for quarterly
  src/modules/companies/controller.js
  src/modules/companies/routes.js
Labels: housekeeping
